version: '3.11'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0
    volumes:
      - .:/app  # Monta el directorio actual en el contenedor para facilitar el desarrollo
